spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://xxxx:3306/db1?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: xxxxx
  redis:
    host: xxxxx
    port: 6379
    password: 123456
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
server:
  port: 8080
