spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.105.161.220:3306/db1?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: Zhou236513
  redis:
    host: 123.249.25.35
    port: 6379
    password: 123456
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
server:
  port: 8080